spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
grpc:
  book:
    hostname: localhost
    port: 6565
  bookshelf:
    hostname: localhost
    port: 6566

---
spring:
  profiles: k8s
grpc:
  book:
    hostname: bookservice.bookshelf-system
    port: 6565
  bookshelf:
    hostname: bookshelfservice.bookshelf-system
    port: 6565
