spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
grpc:
  book:
    hostname: localhost
    port: 6565

---
spring:
  profiles: k8s
grpc:
  book:
    hostname: bookservice.bookshelf-system
    port: 6565
