spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
server.port: 8091
grpc.port: 6566

---
spring:
  profiles: k8s
  datasource:
    url: jdbc:postgresql://bookshelf-db.bookshelf-system:5432/bookshelf
    username: user
    password: password
    driverClassName: org.postgresql.Driver
